/* eslint-disable react/no-array-index-key */
import { Button, Modal } from '@shopify/polaris';
import React, { useState } from 'react';
import styles from './ChangeTheme.module.scss';

const sales = [
  {
    text: {
      title: 'Hurry up - OFF 50% only this week',
      color: '#ffffff',
      font_size: '16',
      visible: true,
      mobile_title: 'Hurry up - OFF 50% only this week',
      mobile_visible: true,
      mobile_color: '#ffffff',
      mobile_font_size: '16',
      font: 'Josefin Sans',
      mobile_font: 'Josefin Sans'
    },
    banner: {
      margin_top: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '5',
      radius: '0',
      border_size: '0',
      background: '#111111',
      border_color: '#000000',
      align_element: 'center',
      background_image: '',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      mobile_padding_horizontal: '8',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_border_size: '0',
      mobile_background: '#111111',
      mobile_border_color: '#000000',
      mobile_align_element: 'center',
      mobile_background_image: ''
    },
    button: {
      title: 'Shop now',
      color: '#000000',
      font_size: '16',
      background: '#ffffff',
      border_color: '#ffffff',
      border_size: '0',
      radius: '30',
      visible: true,
      mobile_title: 'Shop now',
      mobile_visible: true,
      mobile_color: '#000000',
      mobile_font_size: '16',
      mobile_background: '#ffffff',
      mobile_border_size: '0',
      mobile_radius: '30',
      mobile_border_color: '#ffffff',
      font: 'Open Sans',
      mobile_font: 'Open Sans'
    },
    logo: {
      size: '30',
      radius: '0',
      background: '#ffffff00',
      image: '',
      visible: false,
      mobile_size: '50',
      mobile_radius: '0',
      mobile_background: '#ffffff00',
      mobile_image: '',
      mobile_visible: false
    }
  },
  {
    text: {
      title: 'Hurry up - OFF 50% only this week',
      color: '#ffffff',
      font_size: '16',
      visible: true,
      mobile_title: 'Hurry up - OFF 50% only this week',
      mobile_visible: true,
      mobile_color: '#ffffff',
      mobile_font_size: '16',
      font: 'Josefin Sans',
      mobile_font: 'Josefin Sans'
    },
    banner: {
      margin_top: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '5',
      radius: '0',
      border_size: '0',
      background: '#6C070E',
      border_color: '#000000',
      align_element: 'center',
      background_image: '',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      mobile_padding_horizontal: '8',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_border_size: '0',
      mobile_background: '#6C070E',
      mobile_border_color: '#000000',
      mobile_align_element: 'center',
      mobile_background_image: ''
    },
    button: {
      title: 'Shop now',
      color: '#000000',
      font_size: '16',
      background: '#ffffff',
      border_color: '#ffffff',
      border_size: '0',
      radius: '30',
      visible: true,
      mobile_title: 'Shop now',
      mobile_visible: true,
      mobile_color: '#000000',
      mobile_font_size: '16',
      mobile_background: '#ffffff',
      mobile_border_size: '0',
      mobile_radius: '30',
      mobile_border_color: '#ffffff',
      font: 'Open Sans',
      mobile_font: 'Open Sans'
    },
    logo: {
      size: '30',
      radius: '0',
      background: '#ffffff00',
      image: '',
      visible: false,
      mobile_size: '50',
      mobile_radius: '0',
      mobile_background: '#ffffff00',
      mobile_image: '',
      mobile_visible: false
    }
  },
  {
    text: {
      title: 'Hurry up - OFF 50% only this week',
      color: '#ffffff',
      font_size: '16',
      visible: true,
      mobile_title: 'Hurry up - OFF 50% only this week',
      mobile_visible: true,
      mobile_color: '#ffffff',
      mobile_font_size: '16',
      font: 'Josefin Sans',
      mobile_font: 'Josefin Sans'
    },
    banner: {
      margin_top: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '5',
      radius: '0',
      border_size: '0',
      background: '#8CB49D',
      border_color: '#000000',
      align_element: 'center',
      background_image: '',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      mobile_padding_horizontal: '8',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_border_size: '0',
      mobile_background: '#8CB49D',
      mobile_border_color: '#000000',
      mobile_align_element: 'center',
      mobile_background_image: ''
    },
    button: {
      title: 'Shop now',
      color: '#000000',
      font_size: '16',
      background: '#ffffff',
      border_color: '#ffffff',
      border_size: '0',
      radius: '30',
      visible: true,
      mobile_title: 'Shop now',
      mobile_visible: true,
      mobile_color: '#000000',
      mobile_font_size: '16',
      mobile_background: '#ffffff',
      mobile_border_size: '0',
      mobile_radius: '30',
      mobile_border_color: '#ffffff',
      font: 'Open Sans',
      mobile_font: 'Open Sans'
    },
    logo: {
      size: '30',
      radius: '0',
      background: '#ffffff00',
      image: '',
      visible: false,
      mobile_size: '50',
      mobile_radius: '0',
      mobile_background: '#ffffff00',
      mobile_image: '',
      mobile_visible: false
    }
  },
  {
    text: {
    title: 'Limited Time Offer',
    color: '#FFFFFF',
    font_size: '20',
    visible: true,
    mobile_title: 'Limited Time Offer',
    mobile_visible: true,
    mobile_color: '#FFFFFF',
    mobile_font_size: '18',
    font: 'Roboto',
    mobile_font: 'Roboto'
    },
    banner: {
    margin_top: '0',
    margin_horizontal: '0',
    padding_horizontal: '5',
    padding_vertical: '5',
    radius: '0',
    border_size: '0',
    background: '#E74C3C',
    border_color: '#404854',
    align_element: 'center',
    background_image: '',
    mobile_margin_top: '0',
    mobile_margin_horizontal: '0',
    mobile_padding_horizontal: '8',
    mobile_padding_vertical: '5',
    mobile_radius: '0',
    mobile_border_size: '0',
    mobile_background: '#E74C3C',
    mobile_border_color: '#404854',
    mobile_align_element: 'center',
    mobile_background_image: '',
    image_repeat: true,
    mobile_image_repeat: true
    },
    button: {
    title: 'Shop Now',
    color: '#FFFFFF',
    font_size: '17',
    background: '#404854',
    border_color: '#404854',
    border_size: '0',
    radius: '5',
    visible: true,
    mobile_title: 'Shop Now',
    mobile_visible: true,
    mobile_color: '#FFFFFF',
    mobile_font_size: '14',
    mobile_background: '#404854', 
    mobile_border_size: '0',
    mobile_radius: '5',
    mobile_border_color: '#404854',
    font: 'Raleway',
    mobile_font: 'Raleway'
    },
    logo: {
    size: '30',
    radius: '0',
    background: '#ffffff00',
    image: 'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com.png?=1657094663804',
    visible: true,
    mobile_size: '50',
    mobile_radius: '0',
    mobile_background: '#ffffff00',
    mobile_image: 'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com.png?=1657095097449',
    mobile_visible: true
    }
    },
    {
      text: {
        title: '                 Free shipping above on orders $200',
        color: '#ffffff',
        font_size: '16',
        visible: true,
        mobile_title: '                 Free shipping above on orders $200',
        mobile_visible: true,
        mobile_color: '#ffffff',
        mobile_font_size: '16',
        font: 'Lora',
        mobile_font: 'Lora'
      },
      banner: {
        margin_top: '0',
        margin_horizontal: '0',
        padding_horizontal: '5',
        padding_vertical: '5',
        radius: '0',
        border_size: '0',
        background: '#E19993',
        border_color: '#78aee7',
        align_element: 'center',
        background_image: '',
        mobile_margin_top: '0',
        mobile_margin_horizontal: '0',
        mobile_padding_horizontal: '8',
        mobile_padding_vertical: '5',
        mobile_radius: '0',
        mobile_border_size: '0',
        mobile_background: '#E19993',
        mobile_border_color: '#78aee7',
        mobile_align_element: 'center',
        mobile_background_image: ''
      },
      button: {
        title: 'Learn More',
        color: '#000000',
        font_size: '15',
        background: '#FAD43E',
        border_color: '#FAD43E',
        border_size: '0',
        radius: '5',
        visible: false,
        mobile_title: 'Learn More',
        mobile_visible: false,
        mobile_color: '#000000',
        mobile_font_size: '11',
        mobile_background: '#FAD43E',
        mobile_border_size: '0',
        mobile_radius: '5',
        mobile_border_color: '#FAD43E'
      },
      logo: {
        size: '30',
        radius: '0',
        background: '#ffffff00',
        image: '',
        visible: false,
        mobile_size: '50',
        mobile_radius: '0',
        mobile_background: '#ffffff00',
        mobile_image: '',
        mobile_visible: false
      }
    },
    {
      text: {
        title: 'New Arrivals in Store',
        color: '#FC4A1A',
        font_size: '22',
        visible: true,
        mobile_title: 'New Arrivals in Store',
        mobile_visible: true,
        mobile_color: '#FC4A1A',
        mobile_font_size: '22',
        font: 'Oswald',
        mobile_font: 'Oswald'
      },
      banner: {
        margin_top: '0',
        margin_horizontal: '0',
        padding_horizontal: '5',
        padding_vertical: '5',
        radius: '0',
        border_size: '0',
        background: '#FFFFFF',
        border_color: '#E5E5E5',
        align_element: 'center',
        background_image: '',
        mobile_margin_top: '0',
        mobile_margin_horizontal: '0',
        mobile_padding_horizontal: '8',
        mobile_padding_vertical: '5',
        mobile_radius: '0',
        mobile_border_size: '0',
        mobile_background: '#FFFFFF',
        mobile_border_color: '#E5E5E5',
        mobile_align_element: 'center',
        mobile_background_image: '',
        image_repeat: true,
        mobile_image_repeat: true
      },
      button: {
        title: 'Shop Now',
        color: '#FFFFFF',
        font_size: '18',
        background: '#FC4A1A',
        border_color: '#FC4A1A',
        border_size: '0',
        radius: '5',
        visible: true,
        mobile_title: 'Shop Now',
        mobile_visible: true,
        mobile_color: '#FFFFFF',
        mobile_font_size: '18',
        mobile_background: '#FC4A1A',
        mobile_border_size: '0',
        mobile_radius: '5',
        mobile_border_color: '#FC4A1A',
        font: 'Vidaloka',
        mobile_font: 'Vidaloka'
      },
      logo: {
        size: '50',
        radius: '0',
        background: '#ffffff00',
        image: 'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1675190107949.png?=1675190108622',
        visible: true,
        mobile_size: '50',
        mobile_radius: '0',
        mobile_background: '#ffffff00',
        mobile_image: 'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1675190107949.png?=1675190108678',
        mobile_visible: true
      }
    },
    {
      text: {
        title: '                 Free Shipping On Domestic Orders Over $150',
        color: '#ffffff',
        font_size: '16',
        visible: true,
        mobile_title: '                 Free Shipping On Domestic Orders Over $150',
        mobile_visible: true,
        mobile_color: '#ffffff',
        mobile_font_size: '16',
        font: 'Noto Sans',
        mobile_font: 'Noto Sans'
      },
      banner: {
        margin_top: '0',
        margin_horizontal: '0',
        padding_horizontal: '5',
        padding_vertical: '5',
        radius: '0',
        border_size: '0',
        background: '#074A5F',
        border_color: '#78aee7',
        align_element: 'center',
        background_image: '',
        mobile_margin_top: '0',
        mobile_margin_horizontal: '0',
        mobile_padding_horizontal: '8',
        mobile_padding_vertical: '5',
        mobile_radius: '0',
        mobile_border_size: '0',
        mobile_background: '#074A5F',
        mobile_border_color: '#78aee7',
        mobile_align_element: 'center',
        mobile_background_image: ''
      },
      button: {
        title: 'Learn More',
        color: '#000000',
        font_size: '15',
        background: '#FAD43E',
        border_color: '#FAD43E',
        border_size: '0',
        radius: '5',
        visible: false,
        mobile_title: 'Learn More',
        mobile_visible: false,
        mobile_color: '#000000',
        mobile_font_size: '11',
        mobile_background: '#FAD43E',
        mobile_border_size: '0',
        mobile_radius: '5',
        mobile_border_color: '#FAD43E'
      },
      logo: {
        size: '30',
        radius: '0',
        background: '#ffffff00',
        image: '',
        visible: false,
        mobile_size: '50',
        mobile_radius: '0',
        mobile_background: '#ffffff00',
        mobile_image: '',
        mobile_visible: false
      }
    },
    {
      text: {
        title: 'We ship nationwide. 30-day return policy. Free standard shipping on orders over $75. ',
        color: '#ffffff',
        font_size: '16',
        visible: true,
        mobile_title: 'We ship nationwide. 30-day return policy. Free standard shipping on orders over $75. ',
        mobile_visible: true,
        mobile_color: '#ffffff',
        mobile_font_size: '16',
        font: 'Lora',
        mobile_font: 'Lora'
      },
      banner: {
        margin_top: '0',
        margin_horizontal: '0',
        padding_horizontal: '5',
        padding_vertical: '5',
        radius: '0',
        border_size: '0',
        background: '#9ea18e',
        border_color: '#78aee7',
        align_element: 'center',
        background_image: '',
        mobile_margin_top: '0',
        mobile_margin_horizontal: '0',
        mobile_padding_horizontal: '8',
        mobile_padding_vertical: '5',
        mobile_radius: '0',
        mobile_border_size: '0',
        mobile_background: '#9ea18e',
        mobile_border_color: '#78aee7',
        mobile_align_element: 'center',
        mobile_background_image: ''
      },
      button: {
        title: 'Learn More',
        color: '#000000',
        font_size: '15',
        background: '#FAD43E',
        border_color: '#FAD43E',
        border_size: '0',
        radius: '5',
        visible: false,
        mobile_title: 'Learn More',
        mobile_visible: false,
        mobile_color: '#000000',
        mobile_font_size: '11',
        mobile_background: '#FAD43E',
        mobile_border_size: '0',
        mobile_radius: '5',
        mobile_border_color: '#FAD43E'
      },
      logo: {
        size: '30',
        radius: '0',
        background: '#ffffff00',
        image: '',
        visible: false,
        mobile_size: '50',
        mobile_radius: '0',
        mobile_background: '#ffffff00',
        mobile_image: '',
        mobile_visible: false
      }
    },
  {

    text: {
      title: 'Free Shipping on All Orders',
      color: '#FAD43E',
      font_size: '18',
      visible: true,
      mobile_title: 'Free Shipping on All Orders',
      mobile_visible: true,
      mobile_color: '#FAD43E',
      mobile_font_size: '14',
      font: 'Archivo',
      mobile_font: 'Archivo'
    },
    banner: {
      margin_top: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '5',
      radius: '0',
      border_size: '0',
      background: '#0064ff',
      border_color: '#404854',
      align_element: 'center',
      background_image: '',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      mobile_padding_horizontal: '8',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_border_size: '0',
      mobile_background: '#0064ff',
      mobile_border_color: '#404854',
      mobile_align_element: 'center',
      mobile_background_image: '',
      image_repeat: true,
      mobile_image_repeat: true
    },
    button: {
      title: 'Learn More',
      color: '#000000',
      font_size: '15',
      background: '#FAD43E',
      border_color: '#FAD43E',
      border_size: '0',
      radius: '5',
      visible: true,
      mobile_title: 'Learn More',
      mobile_visible: true,
      mobile_color: '#000000',
      mobile_font_size: '11',
      mobile_background: '#FAD43E',
      mobile_border_size: '0',
      mobile_radius: '5',
      mobile_border_color: '#FAD43E',
      font: 'Vidaloka',
      mobile_font: 'Vidaloka'
    },
    logo: {
      size: '30',
      radius: '0',
      background: '#ffffff00',
      image: 'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com.png?=1657094663804',
      visible: true,
      mobile_size: '50',
      mobile_radius: '0',
      mobile_background: '#ffffff00',
      mobile_image: 'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com.png?=1657095097449',
      mobile_visible: true
    }
  },
  {
    text: {
      title: '20% OFF YOUR VERY FIRST PURCHASE, USE PROMO CODE: BELLE FASHION',
      color: '#ffffff',
      font_size: '14',
      visible: true,
      mobile_title: '20% OFF YOUR VERY FIRST PURCHASE, USE PROMO CODE: BELLE FASHION',
      mobile_visible: true,
      mobile_color: '#ffffff',
      mobile_font_size: '14',
      font: 'Lora',
      mobile_font: 'Lora'
    },
    banner: {
      margin_top: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '5',
      radius: '0',
      border_size: '0',
      background: '#31a3a3',
      border_color: '#78aee7',
      align_element: 'center',
      background_image: '',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      mobile_padding_horizontal: '8',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_border_size: '0',
      mobile_background: '#31a3a3',
      mobile_border_color: '#78aee7',
      mobile_align_element: 'center',
      mobile_background_image: ''
    },
    button: {
      title: 'Learn More',
      color: '#000000',
      font_size: '15',
      background: '#FAD43E',
      border_color: '#FAD43E',
      border_size: '0',
      radius: '5',
      visible: false,
      mobile_title: 'Learn More',
      mobile_visible: false,
      mobile_color: '#000000',
      mobile_font_size: '11',
      mobile_background: '#FAD43E',
      mobile_border_size: '0',
      mobile_radius: '5',
      mobile_border_color: '#FAD43E'
    },
    logo: {
      size: '30',
      radius: '0',
      background: '#ffffff00',
      image: '',
      visible: false,
      mobile_size: '50',
      mobile_radius: '0',
      mobile_background: '#ffffff00',
      mobile_image: '',
      mobile_visible: false
    }
  },
  
  {
    
    text: {
      title: 'Save 10% OFF With Promo Code: SAVE10 ⚡',
      color: '#ffffff',
      font_size: '16',
      visible: true,
      mobile_title: 'Save 10% OFF With Promo Code: SAVE10 ⚡',
      mobile_visible: true,
      mobile_color: '#ffffff',
      mobile_font_size: '14',
    },
    banner: {
      margin_top: '0',
      margin_horizontal: '0',
      padding_horizontal: '4',
      padding_vertical: '5',
      radius: '0',
      border_size: '0',
      background: '#2B2B52',
      border_color: '#2B2B52',
      align_element: 'center',
      background_image: '',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      mobile_padding_horizontal: '10',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_border_size: '0',
      mobile_background: '#2B2B52',
      mobile_border_color: '#2B2B52',
      mobile_align_element: 'center',
    },
    button: {
      title: 'APPLY DISCOUNT',
      color: '#ffffff',
      font_size: '14',
      background: '#6d63fc',
      border_color: '#6d63fc',
      border_size: '0',
      radius: '5',
      visible: true,
      mobile_title: 'DISCOUNT',
      mobile_visible: true,
      mobile_color: '#ffffff',
      mobile_font_size: '12',
      mobile_background: '#6d63fc',
      mobile_border_size: '0',
      mobile_radius: '5',
    },
    logo: {
      size: '10',
      radius: '0',
      background: '#ffffff',
      image: '',
      visible: false,
      mobile_size: '10',
      mobile_radius: '0',
      mobile_background: '#ffffff',
      mobile_image: '',
      mobile_visible: false,
    },
  },
  {
    text: {
      title: 'SUMMER SEASON SALE UP TO 90% OFF. USE CODE: SUMMER.',
      color: '#ffffff',
      font_size: '16',
      visible: true,
      mobile_title: 'SUMMER SEASON SALE UP TO 90% OFF. USE CODE: SUMMER.',
      mobile_visible: true,
      mobile_color: '#ffffff',
      mobile_font_size: '16',
      font: 'Josefin Sans',
      mobile_font: 'Josefin Sans'
    },
    banner: {
      margin_top: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '5',
      radius: '0',
      border_size: '0',
      background: '#24ceff',
      border_color: '#000000',
      align_element: 'center',
      background_image: '',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      mobile_padding_horizontal: '8',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_border_size: '0',
      mobile_background: '#24ceff',
      mobile_border_color: '#000000',
      mobile_align_element: 'center',
      mobile_background_image: ''
    },
    button: {
      title: 'Shop now',
      color: '#ffffff',
      font_size: '18',
      background: '#ff358b',
      border_color: '#ffffff',
      border_size: '0',
      radius: '0',
      visible: true,
      mobile_title: 'Shop now',
      mobile_visible: true,
      mobile_color: '#ffffff',
      mobile_font_size: '18',
      mobile_background: '#ff358b',
      mobile_border_size: '0',
      mobile_radius: '0',
      mobile_border_color: '#ffffff'
    },
    logo: {
      size: '30',
      radius: '0',
      background: '#ffffff00',
      image: '',
      visible: false,
      mobile_size: '50',
      mobile_radius: '0',
      mobile_background: '#ffffff00',
      mobile_image: '',
      mobile_visible: false
    }
  },
  {
    text: {
      title: ' Price will increase soon. Get it before time runs out!',
      color: '#ffffff',
      font_size: '16',
      visible: true,
      mobile_title: ' Price will increase soon. Get it before time runs out!',
      mobile_visible: true,
      mobile_color: '#ffffff',
      mobile_font_size: '16',
      font: 'Josefin Sans',
      mobile_font: 'Josefin Sans'
    },
    banner: {
      margin_top: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '5',
      radius: '0',
      border_size: '0',
      background: '#8CB49D',
      border_color: '#000000',
      align_element: 'center',
      background_image: '',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      mobile_padding_horizontal: '8',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_border_size: '0',
      mobile_background: '#8CB49D',
      mobile_border_color: '#000000',
      mobile_align_element: 'center',
      mobile_background_image: ''
    },
    button: {
      title: 'Limited time offer',
      color: '#000000',
      font_size: '16',
      background: '#ffffff',
      border_color: '#ffffff',
      border_size: '0',
      radius: '30',
      visible: true,
      mobile_title: 'Limited time offer',
      mobile_visible: true,
      mobile_color: '#000000',
      mobile_font_size: '16',
      mobile_background: '#ffffff',
      mobile_border_size: '0',
      mobile_radius: '30',
      mobile_border_color: '#ffffff',
      font: 'Open Sans',
      mobile_font: 'Open Sans'
    },
    logo: {
      size: '30',
      radius: '0',
      background: '#ffffff00',
      image: '',
      visible: false,
      mobile_size: '50',
      mobile_radius: '0',
      mobile_background: '#ffffff00',
      mobile_image: '',
      mobile_visible: false
    }
  },
];

const freeshipping = [
  {
    banner: {
      margin_top: '0',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '30',
      radius: 0,
      background: '#000000',
      background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1660903782215.jpg?=1660903782917',
      border_color: '#214259',
      border_size: '0',
      align_element: 'center',
      mobile_padding_horizontal: '5',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_background: '#000000',
      mobile_background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1660903782215.jpg?=1660903782936',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_align_element: 'center',
      image_repeat: false,
      mobile_image_repeat: false,
      image_size: 'cover',
      mobile_image_size: 'cover',
      image_position: 'center',
      mobile_image_position: 'center',
      show_button_close: true,
      mobile_show_button_close: true,
      background_button_close: '#ffffff',
      mobile_background_button_close: '#ffffff',
      size_button_close: '20',
      color_button_close: '#515151',
      mobile_color_button_close: '#515151',
      mobile_size_button_close: '12',
    },
    logo: {
      visible: true,
      image: '',
      background: '#214259',
      radius: 0,
      mobile_visible: true,
      mobile_image: '',
      mobile_background: '#214259',
      mobile_radius: 0,
      size: '0',
      mobile_size: '0',
    },
    text: {
      visible: true,
      title: 'Free shipping today only',
      color: '#fafbfb',
      font_size: '30',
      font: 'Vollkorn',
      mobile_visible: true,
      mobile_title: 'Free shipping today only',
      mobile_color: '#fafbfb',
      mobile_font_size: '30',
      mobile_font: 'Vollkorn',
    },
    button: {
      visible: false,
      title: 'Shop now',
      color: '#fafbfb',
      font_size: '18',
      font: 'Arial',
      border_color: '#214259',
      border_size: 0,
      background: '#006dfd',
      radius: '20',
      mobile_visible: false,
      mobile_title: 'Shop now',
      mobile_color: '#fafbfb',
      mobile_font_size: '18',
      mobile_font: '',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_background: '#006dfd',
      mobile_radius: '20',
    },
  },
  {
    banner: {
      margin_top: '0',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      margin_horizontal: '0',
      padding_horizontal: '0',
      padding_vertical: '10',
      radius: 0,
      background: '#214259',
      background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1658836309348.webp?=1658836309904',
      border_color: '#214259',
      border_size: '0',
      align_element: 'center',
      mobile_padding_horizontal: '0',
      mobile_padding_vertical: '10',
      mobile_radius: '0',
      mobile_background: '#214259',
      mobile_background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1658836309348.webp?=1658836309917',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_align_element: 'center',
    },
    logo: {
      visible: true,
      image: '',
      background: '#214259',
      radius: 0,
      mobile_visible: true,
      mobile_image: '',
      mobile_background: '#214259',
      mobile_radius: 0,
      size: '0',
      mobile_size: '0',
    },
    text: {
      visible: true,
      title: 'Limited-time offer: Get 50% off any product you buy today',
      color: '#fafbfb',
      font_size: '14',
      font: '',
      mobile_visible: true,
      mobile_title: 'Limited-time offer: Get 50% off any product you buy today',
      mobile_color: '#fafbfb',
      mobile_font_size: '14',
      mobile_font: '',
    },
    button: {
      visible: true,
      title: 'Shop now',
      color: '#fafbfb',
      font_size: '18',
      font: '',
      border_color: '#214259',
      border_size: 0,
      background: '#006dfd',
      radius: '20',
      mobile_visible: true,
      mobile_title: 'Shop now',
      mobile_color: '#fafbfb',
      mobile_font_size: '18',
      mobile_font: '',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_background: '#006dfd',
      mobile_radius: '20',
    },
  },
  {
    text: {
      title: 'Free Shipping On All Orders Over $50   🚚',
      color: '#ffffff',
      font_size: '20',
      visible: true,
      mobile_title: 'Free Shipping On All Orders Over $50   🚚',
      mobile_visible: true,
      mobile_color: '#ffffff',
      mobile_font_size: '15',
    },
    banner: {
      margin_top: '0',
      margin_horizontal: '0',
      padding_horizontal: '4',
      padding_vertical: '5',
      radius: '0',
      border_size: '2',
      background: '#7ab0e9',
      border_color: '#7bafe7',
      align_element: 'center',
      background_image: '',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      mobile_padding_horizontal: '4',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_border_size: '2',
      mobile_background: '#7ab0e9',
      mobile_border_color: '#7bafe7',
      mobile_align_element: 'center',
    },
    button: {
      title: 'APPLY DISCOUNT',
      color: '#ffffff',
      font_size: '14',
      background: '#6d63fc',
      border_color: '#6d63fc',
      border_size: '0',
      radius: '5',
      visible: false,
      mobile_title: 'DISCOUNT',
      mobile_visible: false,
      mobile_color: '#ffffff',
      mobile_font_size: '12',
      mobile_background: '#6d63fc',
      mobile_border_size: '0',
      mobile_radius: '5',
    },
    logo: {
      size: '10',
      radius: '0',
      background: '#ffffff',
      image: '',
      visible: false,
      mobile_size: '10',
      mobile_radius: '0',
      mobile_background: '#ffffff',
      mobile_image: '',
      mobile_visible: false,
    },
  },
  {
    text: {
      title: 'Get free shipping when you spend $35 or more',
      color: '#ffffff',
      font_size: '20',
      visible: true,
      mobile_title: 'Get free shipping when you spend $35 or more',
      mobile_visible: true,
      mobile_color: '#ffffff',
      mobile_font_size: '15',
    },
    banner: {
      margin_top: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '5',
      radius: '0',
      border_size: '0',
      background: '#404854',
      border_color: '#404854',
      align_element: 'center',
      background_image: '',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      mobile_padding_horizontal: '5',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_border_size: '0',
      mobile_background: '#404854',
      mobile_border_color: '#404854',
      mobile_align_element: 'center',
    },
    button: {
      title: 'APPLY DISCOUNT',
      color: '#ffffff',
      font_size: '14',
      background: '#6d63fc',
      border_color: '#6d63fc',
      border_size: '0',
      radius: '5',
      visible: false,
      mobile_title: 'DISCOUNT',
      mobile_visible: false,
      mobile_color: '#ffffff',
      mobile_font_size: '12',
      mobile_background: '#6d63fc',
      mobile_border_size: '0',
      mobile_radius: '5',
    },
    logo: {
      size: '30',
      radius: '0',
      background: '#ffffff00',
      image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com.png?=1657094663804',
      visible: true,
      mobile_size: '50',
      mobile_radius: '0',
      mobile_background: '#ffffff00',
      mobile_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com.png?=1657094663809',
      mobile_visible: true,
    },
  },
  {
    text: {
      title: 'Free Shipping on All Orders',
      color: '#FAD43E',
      font_size: '18',
      visible: true,
      mobile_title: 'Free Shipping on All Orders',
      mobile_visible: true,
      mobile_color: '#FAD43E',
      mobile_font_size: '14',
      font: 'Archivo',
      mobile_font: 'Archivo',
    },
    banner: {
      margin_top: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '5',
      radius: '0',
      border_size: '0',
      background: '#404854',
      border_color: '#404854',
      align_element: 'center',
      background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1657095435551.png?=1657095435964',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      mobile_padding_horizontal: '8',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_border_size: '0',
      mobile_background: '#404854',
      mobile_border_color: '#404854',
      mobile_align_element: 'center',
      mobile_background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1657095435551.png?=1657095435971',
      image_repeat: true,
      mobile_image_repeat: true,
    },
    button: {
      title: 'Learn More',
      color: '#000000',
      font_size: '15',
      background: '#FAD43E',
      border_color: '#FAD43E',
      border_size: '0',
      radius: '5',
      visible: true,
      mobile_title: 'Learn More',
      mobile_visible: true,
      mobile_color: '#000000',
      mobile_font_size: '11',
      mobile_background: '#FAD43E',
      mobile_border_size: '0',
      mobile_radius: '5',
      mobile_border_color: '#FAD43E',
      font: 'Vidaloka',
      mobile_font: 'Vidaloka',
    },
    logo: {
      size: '30',
      radius: '0',
      background: '#ffffff00',
      image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com.png?=1657094663804',
      visible: true,
      mobile_size: '50',
      mobile_radius: '0',
      mobile_background: '#ffffff00',
      mobile_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com.png?=1657095097449',
      mobile_visible: true,
    },
  },
  {
    text: {
      title: 'LAST DAY to Enjoy FREE Shipping | Shop Now',
      color: '#5EBEC4',
      font_size: '19',
      visible: true,
      mobile_title: 'LAST DAY to Enjoy FREE Shipping | Shop Now',
      mobile_visible: true,
      mobile_color: '#5EBEC4',
      mobile_font_size: '15',
    },
    banner: {
      margin_top: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '5',
      radius: '0',
      border_size: '0',
      background: '#FDF5DF',
      border_color: '#FDF5DF',
      align_element: 'center',
      background_image: '',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      mobile_padding_horizontal: '8',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_border_size: '0',
      mobile_background: '#FDF5DF',
      mobile_border_color: '#FDF5DF',
      mobile_align_element: 'center',
      mobile_background_image: '',
    },
    button: {
      title: "Let's go",
      color: '#ffffff',
      font_size: '17',
      background: '#F92C85',
      border_color: '#F92C85',
      border_size: '0',
      radius: '6',
      visible: true,
      mobile_title: "Let's go",
      mobile_visible: false,
      mobile_color: '#ffffff',
      mobile_font_size: '11',
      mobile_background: '#F92C85',
      mobile_border_size: '0',
      mobile_radius: '6',
      mobile_border_color: '#F92C85',
    },
    logo: {
      size: '30',
      radius: '13',
      background: '#704a4a00',
      image: '',
      visible: false,
      mobile_size: '50',
      mobile_radius: '13',
      mobile_background: '#704a4a00',
      mobile_image: '',
      mobile_visible: false,
    },
  },
  {
    text: {
      title: 'Free 2-Day Shipping Ends Tonight, Get Your Gifts In Time',
      color: '#000000',
      font_size: '21',
      visible: true,
      mobile_title: 'Free 2-Day Shipping Ends Tonight, Get Your Gifts In Time',
      mobile_visible: true,
      mobile_color: '#000000',
      mobile_font_size: '21',
    },
    banner: {
      margin_top: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '5',
      radius: '0',
      border_size: '0',
      background: '#A0AECD',
      border_color: '#A0AECD',
      align_element: 'center',
      background_image: '',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      mobile_padding_horizontal: '8',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_border_size: '0',
      mobile_background: '#A0AECD',
      mobile_border_color: '#A0AECD',
      mobile_align_element: 'center',
      mobile_background_image: '',
    },
    button: {
      title: "Let's go",
      color: '#ffffff',
      font_size: '17',
      background: '#F92C85',
      border_color: '#F92C85',
      border_size: '0',
      radius: '6',
      visible: false,
      mobile_title: "Let's go",
      mobile_visible: false,
      mobile_color: '#ffffff',
      mobile_font_size: '11',
      mobile_background: '#F92C85',
      mobile_border_size: '0',
      mobile_radius: '6',
      mobile_border_color: '#F92C85',
    },
    logo: {
      size: '30',
      radius: '13',
      background: '#704a4a00',
      image: '',
      visible: false,
      mobile_size: '50',
      mobile_radius: '13',
      mobile_background: '#704a4a00',
      mobile_image: '',
      mobile_visible: false,
    },
  },
  {
    banner: {
      margin_top: '0',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      margin_horizontal: '0',
      padding_horizontal: '41',
      padding_vertical: '5',
      radius: 0,
      background: '#d4b5ed',
      background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659422420856.webp?=1659422421197',
      border_color: '#214259',
      border_size: '0',
      align_element: 'space_between',
      mobile_padding_horizontal: '41',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_background: '#d4b5ed',
      mobile_background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659422420856.webp?=1659422421214',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_align_element: 'space_between',
      image_repeat: false,
      mobile_image_repeat: false,
      image_size: 'contain',
      mobile_image_size: 'contain',
      image_position: 'center',
      mobile_image_position: 'center',
      show_button_close: true,
      mobile_show_button_close: true,
      background_button_close: '#ffffff',
      mobile_background_button_close: '#ffffff',
      size_button_close: '17',
      color_button_close: '#999999',
      mobile_color_button_close: '#999999',
      mobile_size_button_close: '12',
    },
    logo: {
      visible: true,
      image: '',
      background: '#214259',
      radius: 0,
      mobile_visible: true,
      mobile_image: '',
      mobile_background: '#214259',
      mobile_radius: 0,
      size: '0',
      mobile_size: '0',
    },
    text: {
      visible: true,
      title:
        'FREE SHIPPING DEAL - Add to your cart to unlock free shipping upon checkout',
      color: '#000000',
      font_size: '14',
      font: 'Acme',
      mobile_visible: true,
      mobile_title:
        'FREE SHIPPING DEAL - Add to your cart to unlock free shipping upon checkout',
      mobile_color: '#000000',
      mobile_font_size: '11',
      mobile_font: 'Acme',
    },
    button: {
      visible: true,
      title: 'SEE MY CART →',
      color: '#9373AC',
      font_size: '13',
      font: 'Fredoka One',
      border_color: '#ffffff',
      border_size: '0',
      background: '#ffffff',
      radius: '0',
      mobile_visible: true,
      mobile_title: 'SEE MY CART',
      mobile_color: '#9373AC',
      mobile_font_size: '10',
      mobile_font: 'Fredoka One',
      mobile_border_color: '#ffffff',
      mobile_border_size: '0',
      mobile_background: '#ffffff',
      mobile_radius: '0',
    },
  },
];

// const valentinesDay = [

// ];

const tops = [
  {
    banner: {
      margin_top: '0',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '30',
      radius: 0,
      background: '#000000',
      background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659421464988.png?=1659421465692',
      border_color: '#214259',
      border_size: '0',
      align_element: 'center',
      mobile_padding_horizontal: '5',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_background: '#000000',
      mobile_background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659421464988.png?=1659421465708',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_align_element: 'center',
      image_repeat: false,
      mobile_image_repeat: false,
      image_size: 'cover',
      mobile_image_size: 'cover',
      image_position: 'center',
      mobile_image_position: 'center',
      show_button_close: true,
      mobile_show_button_close: true,
      background_button_close: '#ffffff',
      mobile_background_button_close: '#ffffff',
      size_button_close: '20',
      color_button_close: '#515151',
      mobile_color_button_close: '#515151',
      mobile_size_button_close: '12',
    },
    logo: {
      visible: true,
      image: '',
      background: '#214259',
      radius: 0,
      mobile_visible: true,
      mobile_image: '',
      mobile_background: '#214259',
      mobile_radius: 0,
      size: '0',
      mobile_size: '0',
    },
    text: {
      visible: true,
      title: 'Independence Day SALE',
      color: '#fafbfb',
      font_size: '30',
      font: 'Ultra',
      mobile_visible: true,
      mobile_title: 'Independence Day SALE',
      mobile_color: '#fafbfb',
      mobile_font_size: '12',
      mobile_font: 'Ultra',
    },
    button: {
      visible: true,
      title: 'Shop now',
      color: '#fafbfb',
      font_size: '18',
      font: 'Acme',
      border_color: '#ffffff',
      border_size: '1',
      background: '#da0200',
      radius: '0',
      mobile_visible: true,
      mobile_title: 'Shop now',
      mobile_color: '#fafbfb',
      mobile_font_size: '11',
      mobile_font: 'Acme',
      mobile_border_color: '#ffffff',
      mobile_border_size: '1',
      mobile_background: '#da0200',
      mobile_radius: '0',
    },
  },
  {
    banner: {
      margin_top: '0',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '15',
      radius: 0,
      background: '#271036',
      background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659423178999.webp?=1659423179701',
      border_color: '#214259',
      border_size: '0',
      align_element: 'center',
      mobile_padding_horizontal: '5',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_background: '#271036',
      mobile_background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659423178999.webp?=1659423179717',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_align_element: 'center',
      image_repeat: false,
      mobile_image_repeat: false,
      image_size: 'cover',
      mobile_image_size: 'cover',
      image_position: 'center',
      mobile_image_position: 'center',
      show_button_close: true,
      mobile_show_button_close: true,
      background_button_close: '#ffffff',
      mobile_background_button_close: '#ffffff',
      size_button_close: '20',
      color_button_close: '#515151',
      mobile_color_button_close: '#515151',
      mobile_size_button_close: '12',
    },
    logo: {
      visible: true,
      image: '',
      background: '#214259',
      radius: 0,
      mobile_visible: true,
      mobile_image: '',
      mobile_background: '#214259',
      mobile_radius: 0,
      size: '0',
      mobile_size: '0',
    },
    text: {
      visible: true,
      title: 'Halloween sale!',
      color: '#fafbfb',
      font_size: '48',
      font: 'Mansalva',
      mobile_visible: true,
      mobile_title: 'Halloween sale!',
      mobile_color: '#fafbfb',
      mobile_font_size: '20',
      mobile_font: 'Mansalva',
    },
    button: {
      visible: true,
      title: 'Shop now',
      color: '#fafbfb',
      font_size: '18',
      font: 'Acme',
      border_color: '#214259',
      border_size: 0,
      background: '#271036',
      radius: '5',
      mobile_visible: true,
      mobile_title: 'Shop now',
      mobile_color: '#fafbfb',
      mobile_font_size: '18',
      mobile_font: 'Acme',
      mobile_border_color: '#f4f4f4',
      mobile_border_size: '1',
      mobile_background: '#271036',
      mobile_radius: '5',
    },
  },
  {
    banner: {
      margin_top: '0',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '23',
      radius: 0,
      background: '#000000',
      background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659421996702.webp?=1659421997273',
      border_color: '#214259',
      border_size: '0',
      align_element: 'center',
      mobile_padding_horizontal: '5',
      mobile_padding_vertical: '11',
      mobile_radius: '0',
      mobile_background: '#000000',
      mobile_background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659421996702.webp?=1659421997288',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_align_element: 'center',
      image_repeat: false,
      mobile_image_repeat: false,
      image_size: 'cover',
      mobile_image_size: 'cover',
      image_position: 'center',
      mobile_image_position: 'center',
      show_button_close: true,
      mobile_show_button_close: true,
      background_button_close: '#ffffff',
      mobile_background_button_close: '#ffffff',
      size_button_close: '20',
      color_button_close: '#ff6876',
      mobile_color_button_close: '#ff6876',
      mobile_size_button_close: '12',
    },
    logo: {
      visible: true,
      image: '',
      background: '#214259',
      radius: 0,
      mobile_visible: true,
      mobile_image: '',
      mobile_background: '#214259',
      mobile_radius: 0,
      size: '0',
      mobile_size: '0',
    },
    text: {
      visible: true,
      title: "Valentine's Day Sale",
      color: '#fafbfb',
      font_size: '43',
      font: 'Pacifico',
      mobile_visible: true,
      mobile_title: "Valentine's Day Sale",
      mobile_color: '#fafbfb',
      mobile_font_size: '17',
      mobile_font: 'Pacifico',
    },
    button: {
      visible: true,
      title: 'Shop now',
      color: '#ff6876',
      font_size: '18',
      font: 'Acme',
      border_color: '#ff6876',
      border_size: '1',
      background: '#ffffff',
      radius: '0',
      mobile_visible: true,
      mobile_title: 'Shop now',
      mobile_color: '#ff6876',
      mobile_font_size: '11',
      mobile_font: 'Acme',
      mobile_border_color: '#ff6876',
      mobile_border_size: '1',
      mobile_background: '#ffffff',
      mobile_radius: '0',
    },
  },
  {
    banner: {
      margin_top: '0',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '15',
      radius: 0,
      background: '#f9272700',
      background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659548985267.png?=1659548986698',
      border_color: '#214259',
      border_size: '0',
      align_element: 'center',
      mobile_padding_horizontal: '5',
      mobile_padding_vertical: '15',
      mobile_radius: '0',
      mobile_background: '#f9272700',
      mobile_background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659548985267.png?=1659548986714',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_align_element: 'center',
      image_repeat: false,
      mobile_image_repeat: false,
      image_size: 'cover',
      mobile_image_size: 'cover',
      image_position: 'center',
      mobile_image_position: 'right',
      show_button_close: true,
      mobile_show_button_close: true,
      background_button_close: '#ffffff',
      mobile_background_button_close: '#ffffff',
      size_button_close: '20',
      color_button_close: '#515151',
      mobile_color_button_close: '#515151',
      mobile_size_button_close: '12',
    },
    logo: {
      visible: false,
      image: '',
      background: '#214259',
      radius: 0,
      mobile_visible: false,
      mobile_image: '',
      mobile_background: '#214259',
      mobile_radius: 0,
      size: '0',
      mobile_size: '0',
    },
    text: {
      visible: true,
      title: 'SPRING SALE',
      color: '#fafbfb',
      font_size: '48',
      font: 'Bitter',
      mobile_visible: true,
      mobile_title: 'SPRING SALE',
      mobile_color: '#fafbfb',
      mobile_font_size: '20',
      mobile_font: 'Bitter',
    },
    button: {
      visible: true,
      title: 'Get Discount',
      color: '#ffffff',
      font_size: '20',
      font: 'Bitter',
      border_color: '#000000',
      border_size: '0',
      background: '#efd7d7',
      radius: '30',
      mobile_visible: true,
      mobile_title: 'Get Discount',
      mobile_color: '#ffffff',
      mobile_font_size: '16',
      mobile_font: 'Bitter',
      mobile_border_color: '#000000',
      mobile_border_size: '0',
      mobile_background: '#efd7d7',
      mobile_radius: '30',
    },
  },
  {
    banner: {
      margin_top: '0',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '15',
      radius: 0,
      background: '#f92727',
      background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659548436860.webp?=1659548438075',
      border_color: '#214259',
      border_size: '0',
      align_element: 'center',
      mobile_padding_horizontal: '5',
      mobile_padding_vertical: '15',
      mobile_radius: '0',
      mobile_background: '#f92727',
      mobile_background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659548436860.webp?=1659548438095',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_align_element: 'center',
      image_repeat: false,
      mobile_image_repeat: false,
      image_size: 'cover',
      mobile_image_size: 'cover',
      image_position: 'center',
      mobile_image_position: 'left',
      show_button_close: true,
      mobile_show_button_close: true,
      background_button_close: '#ffffff',
      mobile_background_button_close: '#ffffff',
      size_button_close: '20',
      color_button_close: '#515151',
      mobile_color_button_close: '#515151',
      mobile_size_button_close: '12',
    },
    logo: {
      visible: false,
      image: '',
      background: '#214259',
      radius: 0,
      mobile_visible: false,
      mobile_image: '',
      mobile_background: '#214259',
      mobile_radius: 0,
      size: '0',
      mobile_size: '0',
    },
    text: {
      visible: true,
      title: 'Holiday sale',
      color: '#fafbfb',
      font_size: '48',
      font: 'Kalam',
      mobile_visible: true,
      mobile_title: 'Holiday sale',
      mobile_color: '#fafbfb',
      mobile_font_size: '20',
      mobile_font: 'Kalam',
    },
    button: {
      visible: true,
      title: 'Get Discount',
      color: '#fafbfb',
      font_size: '20',
      font: 'Asap',
      border_color: '#000000',
      border_size: '5',
      background: '#271036',
      radius: '0',
      mobile_visible: true,
      mobile_title: 'Get Discount',
      mobile_color: '#ffffff',
      mobile_font_size: '16',
      mobile_font: 'Asap',
      mobile_border_color: '#000000',
      mobile_border_size: '5',
      mobile_background: '#000000',
      mobile_radius: '0',
    },
  },
  {
    banner: {
      margin_top: '0',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '30',
      radius: 0,
      background: '#000000',
      background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659368111454.webp?=1659368112109',
      border_color: '#214259',
      border_size: '0',
      align_element: 'center',
      mobile_padding_horizontal: '5',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_background: '#000000',
      mobile_background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659368111454.webp?=1659368112124',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_align_element: 'center',
      image_repeat: false,
      mobile_image_repeat: false,
      image_size: 'cover',
      mobile_image_size: 'cover',
      image_position: 'center',
      mobile_image_position: 'center',
      show_button_close: true,
      mobile_show_button_close: true,
      background_button_close: '#ffffff',
      mobile_background_button_close: '#ffffff',
      size_button_close: '20',
      color_button_close: '#515151',
      mobile_color_button_close: '#515151',
      mobile_size_button_close: '12',
    },
    logo: {
      visible: true,
      image: '',
      background: '#214259',
      radius: 0,
      mobile_visible: true,
      mobile_image: '',
      mobile_background: '#214259',
      mobile_radius: 0,
      size: '0',
      mobile_size: '0',
    },
    text: {
      visible: true,
      title: 'BLACK FRIDAY SALE',
      color: '#fafbfb',
      font_size: '30',
      font: 'Acme',
      mobile_visible: true,
      mobile_title: 'BLACK FRIDAY SALE',
      mobile_color: '#fafbfb',
      mobile_font_size: '13',
      mobile_font: '',
    },
    button: {
      visible: false,
      title: 'Shop now',
      color: '#fafbfb',
      font_size: '18',
      font: 'Arial',
      border_color: '#214259',
      border_size: 0,
      background: '#006dfd',
      radius: '20',
      mobile_visible: false,
      mobile_title: 'Shop now',
      mobile_color: '#fafbfb',
      mobile_font_size: '18',
      mobile_font: '',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_background: '#006dfd',
      mobile_radius: '20',
    },
  },
];

const holidays = [
  {
    banner: {
      margin_top: '0',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '30',
      radius: 0,
      background: '#000000',
      background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659421464988.png?=1659421465692',
      border_color: '#214259',
      border_size: '0',
      align_element: 'center',
      mobile_padding_horizontal: '5',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_background: '#000000',
      mobile_background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659421464988.png?=1659421465708',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_align_element: 'center',
      image_repeat: false,
      mobile_image_repeat: false,
      image_size: 'cover',
      mobile_image_size: 'cover',
      image_position: 'center',
      mobile_image_position: 'center',
      show_button_close: true,
      mobile_show_button_close: true,
      background_button_close: '#ffffff',
      mobile_background_button_close: '#ffffff',
      size_button_close: '20',
      color_button_close: '#515151',
      mobile_color_button_close: '#515151',
      mobile_size_button_close: '12',
    },
    logo: {
      visible: true,
      image: '',
      background: '#214259',
      radius: 0,
      mobile_visible: true,
      mobile_image: '',
      mobile_background: '#214259',
      mobile_radius: 0,
      size: '0',
      mobile_size: '0',
    },
    text: {
      visible: true,
      title: 'Independence Day SALE',
      color: '#fafbfb',
      font_size: '30',
      font: 'Ultra',
      mobile_visible: true,
      mobile_title: 'Independence Day SALE',
      mobile_color: '#fafbfb',
      mobile_font_size: '12',
      mobile_font: 'Ultra',
    },
    button: {
      visible: true,
      title: 'Shop now',
      color: '#fafbfb',
      font_size: '18',
      font: 'Acme',
      border_color: '#ffffff',
      border_size: '1',
      background: '#da0200',
      radius: '0',
      mobile_visible: true,
      mobile_title: 'Shop now',
      mobile_color: '#fafbfb',
      mobile_font_size: '11',
      mobile_font: 'Acme',
      mobile_border_color: '#ffffff',
      mobile_border_size: '1',
      mobile_background: '#da0200',
      mobile_radius: '0',
    },
  },
  {
    banner: {
      margin_top: '0',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '30',
      radius: 0,
      background: '#000000',
      background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659368111454.webp?=1659368112109',
      border_color: '#214259',
      border_size: '0',
      align_element: 'center',
      mobile_padding_horizontal: '5',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_background: '#000000',
      mobile_background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659368111454.webp?=1659368112124',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_align_element: 'center',
      image_repeat: false,
      mobile_image_repeat: false,
      image_size: 'cover',
      mobile_image_size: 'cover',
      image_position: 'center',
      mobile_image_position: 'center',
      show_button_close: true,
      mobile_show_button_close: true,
      background_button_close: '#ffffff',
      mobile_background_button_close: '#ffffff',
      size_button_close: '20',
      color_button_close: '#515151',
      mobile_color_button_close: '#515151',
      mobile_size_button_close: '12',
    },
    logo: {
      visible: true,
      image: '',
      background: '#214259',
      radius: 0,
      mobile_visible: true,
      mobile_image: '',
      mobile_background: '#214259',
      mobile_radius: 0,
      size: '0',
      mobile_size: '0',
    },
    text: {
      visible: true,
      title: 'BLACK FRIDAY SALE',
      color: '#fafbfb',
      font_size: '30',
      font: 'Acme',
      mobile_visible: true,
      mobile_title: 'BLACK FRIDAY SALE',
      mobile_color: '#fafbfb',
      mobile_font_size: '13',
      mobile_font: '',
    },
    button: {
      visible: false,
      title: 'Shop now',
      color: '#fafbfb',
      font_size: '18',
      font: 'Arial',
      border_color: '#214259',
      border_size: 0,
      background: '#006dfd',
      radius: '20',
      mobile_visible: false,
      mobile_title: 'Shop now',
      mobile_color: '#fafbfb',
      mobile_font_size: '18',
      mobile_font: '',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_background: '#006dfd',
      mobile_radius: '20',
    },
  },
  {
    text: {
      title: ' BLACK FRIDAY SALE',
      color: '#ffffff',
      font_size: '24',
      visible: true,
      mobile_title: ' BLACK FRIDAY SALE',
      mobile_visible: true,
      mobile_color: '#ffffff',
      mobile_font_size: '24',
      font: 'Vidaloka',
    },
    banner: {
      margin_top: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '5',
      radius: '0',
      border_size: '0',
      background: '#404854',
      border_color: '#404854',
      align_element: 'center',
      background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/test-store-3532534536.myshopify.com/img_1659391271628.webp?=1659391270223',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      mobile_padding_horizontal: '8',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_border_size: '0',
      mobile_background: '#404854',
      mobile_border_color: '#404854',
      mobile_align_element: 'center',
      mobile_background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/test-store-3532534536.myshopify.com/img_1659391271628.webp?=1659391270230',
      image_repeat: false,
      mobile_image_repeat: false,
      image_size: 'cover',
      mobile_image_size: 'cover',
      image_position: 'bottom',
      mobile_image_position: 'bottom',
      show_button_close: true,
      mobile_show_button_close: true,
      background_button_close: '#00000000',
      mobile_background_button_close: '#00000000',
      color_button_close: '#000000',
      mobile_color_button_close: '#000000',
      size_button_close: '20',
    },
    button: {
      title: 'Get Discount',
      color: '#000000',
      font_size: '15',
      background: 'gradient_pink',
      border_color: '#ff3b50',
      border_size: '0',
      radius: '5',
      visible: true,
      mobile_title: 'Get Discount',
      mobile_visible: true,
      mobile_color: '#000000',
      mobile_font_size: '11',
      mobile_background: '#a94343',
      mobile_border_size: '0',
      mobile_radius: '5',
      mobile_border_color: '#ff3b50',
      font: 'Bitter',
    },
    logo: {
      size: '30',
      radius: '0',
      background: '#ffffff00',
      image: '',
      visible: true,
      mobile_size: '0',
      mobile_radius: '0',
      mobile_background: '#ffffff00',
      mobile_image: '',
      mobile_visible: true,
    },
  },
  {
    banner: {
      margin_top: '0',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '15',
      radius: 0,
      background: '#271036',
      background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659423178999.webp?=1659423179701',
      border_color: '#214259',
      border_size: '0',
      align_element: 'center',
      mobile_padding_horizontal: '5',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_background: '#271036',
      mobile_background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659423178999.webp?=1659423179717',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_align_element: 'center',
      image_repeat: false,
      mobile_image_repeat: false,
      image_size: 'cover',
      mobile_image_size: 'cover',
      image_position: 'center',
      mobile_image_position: 'center',
      show_button_close: true,
      mobile_show_button_close: true,
      background_button_close: '#ffffff',
      mobile_background_button_close: '#ffffff',
      size_button_close: '20',
      color_button_close: '#515151',
      mobile_color_button_close: '#515151',
      mobile_size_button_close: '12',
    },
    logo: {
      visible: true,
      image: '',
      background: '#214259',
      radius: 0,
      mobile_visible: true,
      mobile_image: '',
      mobile_background: '#214259',
      mobile_radius: 0,
      size: '0',
      mobile_size: '0',
    },
    text: {
      visible: true,
      title: 'Halloween sale!',
      color: '#fafbfb',
      font_size: '48',
      font: 'Mansalva',
      mobile_visible: true,
      mobile_title: 'Halloween sale!',
      mobile_color: '#fafbfb',
      mobile_font_size: '20',
      mobile_font: 'Mansalva',
    },
    button: {
      visible: true,
      title: 'Shop now',
      color: '#fafbfb',
      font_size: '18',
      font: 'Acme',
      border_color: '#214259',
      border_size: 0,
      background: '#271036',
      radius: '5',
      mobile_visible: true,
      mobile_title: 'Shop now',
      mobile_color: '#fafbfb',
      mobile_font_size: '18',
      mobile_font: 'Acme',
      mobile_border_color: '#f4f4f4',
      mobile_border_size: '1',
      mobile_background: '#271036',
      mobile_radius: '5',
    },
  },
  {
    banner: {
      margin_top: '0',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '23',
      radius: 0,
      background: '#000000',
      background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659421996702.webp?=1659421997273',
      border_color: '#214259',
      border_size: '0',
      align_element: 'center',
      mobile_padding_horizontal: '5',
      mobile_padding_vertical: '11',
      mobile_radius: '0',
      mobile_background: '#000000',
      mobile_background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659421996702.webp?=1659421997288',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_align_element: 'center',
      image_repeat: false,
      mobile_image_repeat: false,
      image_size: 'cover',
      mobile_image_size: 'cover',
      image_position: 'center',
      mobile_image_position: 'center',
      show_button_close: true,
      mobile_show_button_close: true,
      background_button_close: '#ffffff',
      mobile_background_button_close: '#ffffff',
      size_button_close: '20',
      color_button_close: '#ff6876',
      mobile_color_button_close: '#ff6876',
      mobile_size_button_close: '12',
    },
    logo: {
      visible: true,
      image: '',
      background: '#214259',
      radius: 0,
      mobile_visible: true,
      mobile_image: '',
      mobile_background: '#214259',
      mobile_radius: 0,
      size: '0',
      mobile_size: '0',
    },
    text: {
      visible: true,
      title: "Valentine's Day Sale",
      color: '#fafbfb',
      font_size: '43',
      font: 'Pacifico',
      mobile_visible: true,
      mobile_title: "Valentine's Day Sale",
      mobile_color: '#fafbfb',
      mobile_font_size: '17',
      mobile_font: 'Pacifico',
    },
    button: {
      visible: true,
      title: 'Shop now',
      color: '#ff6876',
      font_size: '18',
      font: 'Acme',
      border_color: '#ff6876',
      border_size: '1',
      background: '#ffffff',
      radius: '0',
      mobile_visible: true,
      mobile_title: 'Shop now',
      mobile_color: '#ff6876',
      mobile_font_size: '11',
      mobile_font: 'Acme',
      mobile_border_color: '#ff6876',
      mobile_border_size: '1',
      mobile_background: '#ffffff',
      mobile_radius: '0',
    },
  },
  {
    text: {
      title: 'Love Free Shipping? Order Before Valentine’s Day 🚢❤️',
      color: '#ffffff',
      font_size: '21',
      visible: true,
      mobile_title: 'Love Free Shipping? Order Before Valentine’s Day 🚢❤️',
      mobile_visible: true,
      mobile_color: '#ffffff',
      mobile_font_size: '15',
    },
    banner: {
      margin_top: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '5',
      radius: '0',
      border_size: '0',
      background: '#00ABE1',
      border_color: '#00ABE1',
      align_element: 'center',
      background_image: '',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      mobile_padding_horizontal: '8',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_border_size: '0',
      mobile_background: '#00ABE1',
      mobile_border_color: '#00ABE1',
      mobile_align_element: 'center',
      mobile_background_image: '',
    },
    button: {
      title: "Let's go",
      color: '#ffffff',
      font_size: '17',
      background: '#161F6D',
      border_color: '#161F6D',
      border_size: '0',
      radius: '6',
      visible: true,
      mobile_title: "Let's go",
      mobile_visible: false,
      mobile_color: '#ffffff',
      mobile_font_size: '12',
      mobile_background: '#161F6D',
      mobile_border_size: '0',
      mobile_radius: '6',
      mobile_border_color: '#161F6D',
    },
    logo: {
      size: '30',
      radius: '13',
      background: '#704a4a00',
      image: '',
      visible: false,
      mobile_size: '50',
      mobile_radius: '13',
      mobile_background: '#704a4a00',
      mobile_image: '',
      mobile_visible: false,
    },
  },
  {
    text: {
      title:
        'Roses are Red, Violets are Blue, All Items are 10% off, Just for You',
      color: '#000000',
      font_size: '21',
      visible: true,
      mobile_title:
        'Roses are Red, Violets are Blue, All Items are 10% off, Just for You',
      mobile_visible: true,
      mobile_color: '#000000',
      mobile_font_size: '13',
    },
    banner: {
      margin_top: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '5',
      radius: '0',
      border_size: '0',
      background: '#E1F2F7',
      border_color: '#00ABE1',
      align_element: 'center',
      background_image: '',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      mobile_padding_horizontal: '8',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_border_size: '0',
      mobile_background: '#E1F2F7',
      mobile_border_color: '#00ABE1',
      mobile_align_element: 'center',
      mobile_background_image: '',
    },
    button: {
      title: "Let's go",
      color: '#ffffff',
      font_size: '17',
      background: '#EF0D50',
      border_color: '#EF0D50',
      border_size: '0',
      radius: '6',
      visible: true,
      mobile_title: 'Go',
      mobile_visible: true,
      mobile_color: '#ffffff',
      mobile_font_size: '14',
      mobile_background: '#EF0D50',
      mobile_border_size: '0',
      mobile_radius: '6',
      mobile_border_color: '#EF0D50',
    },
    logo: {
      size: '30',
      radius: '13',
      background: '#704a4a00',
      image: '',
      visible: false,
      mobile_size: '50',
      mobile_radius: '13',
      mobile_background: '#704a4a00',
      mobile_image: '',
      mobile_visible: false,
    },
  },
  {
    text: {
      title: 'Last Chance For Free Shipping In Time For Valentine’s Day',
      color: '#0B4141',
      font_size: '21',
      visible: true,
      mobile_title: 'Last Chance For Free Shipping In Time For Valentine’s Day',
      mobile_visible: true,
      mobile_color: '#0B4141',
      mobile_font_size: '13',
    },
    banner: {
      margin_top: '4',
      margin_horizontal: '6',
      padding_horizontal: '5',
      padding_vertical: '5',
      radius: '8',
      border_size: '1',
      background: '#FAF0DC',
      border_color: '#faf0dc',
      align_element: 'center',
      background_image: '',
      mobile_margin_top: '14',
      mobile_margin_horizontal: '6',
      mobile_padding_horizontal: '5',
      mobile_padding_vertical: '5',
      mobile_radius: '8',
      mobile_border_size: '1',
      mobile_background: '#FAF0DC',
      mobile_border_color: '#faf0dc',
      mobile_align_element: 'center',
      mobile_background_image: '',
    },
    button: {
      title: "Let's go",
      color: '#ffffff',
      font_size: '17',
      background: '#FF6864',
      border_color: '#FF6864',
      border_size: '0',
      radius: '6',
      visible: true,
      mobile_title: 'Go',
      mobile_visible: true,
      mobile_color: '#ffffff',
      mobile_font_size: '14',
      mobile_background: '#FF6864',
      mobile_border_size: '0',
      mobile_radius: '6',
      mobile_border_color: '#FF6864',
    },
    logo: {
      size: '30',
      radius: '13',
      background: '#704a4a00',
      image: '',
      visible: false,
      mobile_size: '50',
      mobile_radius: '13',
      mobile_background: '#704a4a00',
      mobile_image: '',
      mobile_visible: false,
    },
  },
  {
    text: {
      title: 'Get These Valentine’s Day Deals Before Time Runs Out',
      color: '#faffff',
      font_size: '21',
      visible: true,
      mobile_title: 'Get These Valentine’s Day Deals Before Time Runs Out',
      mobile_visible: true,
      mobile_color: '#faffff',
      mobile_font_size: '13',
    },
    banner: {
      margin_top: '2',
      margin_horizontal: '2',
      padding_horizontal: '5',
      padding_vertical: '5',
      radius: '0',
      border_size: '4',
      background: '#C39EA0',
      border_color: '#F8E5E5',
      align_element: 'center',
      background_image: '',
      mobile_margin_top: '2',
      mobile_margin_horizontal: '2',
      mobile_padding_horizontal: '5',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_border_size: '4',
      mobile_background: '#C39EA0',
      mobile_border_color: '#F8E5E5',
      mobile_align_element: 'center',
      mobile_background_image: '',
    },
    button: {
      title: "Let's go",
      color: '#ffffff',
      font_size: '17',
      background: '#FF6864',
      border_color: '#FF6864',
      border_size: '0',
      radius: '6',
      visible: false,
      mobile_title: 'Go',
      mobile_visible: false,
      mobile_color: '#ffffff',
      mobile_font_size: '14',
      mobile_background: '#FF6864',
      mobile_border_size: '0',
      mobile_radius: '6',
      mobile_border_color: '#FF6864',
    },
    logo: {
      size: '30',
      radius: '13',
      background: '#704a4a00',
      image: '',
      visible: false,
      mobile_size: '50',
      mobile_radius: '13',
      mobile_background: '#704a4a00',
      mobile_image: '',
      mobile_visible: false,
    },
  },
  {
    text: {
      title: 'You Haven’t Left Valentine’s Too Late: Free Express Shipping! ',
      color: '#fcfcfc',
      font_size: '21',
      visible: true,
      mobile_title:
        'You Haven’t Left Valentine’s Too Late: Free Express Shipping! ',
      mobile_visible: true,
      mobile_color: '#fcfcfc',
      mobile_font_size: '13',
    },
    banner: {
      margin_top: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '5',
      radius: '0',
      border_size: '0',
      background: '#4AC6D2',
      border_color: '#4AC6D2',
      align_element: 'center',
      background_image: '',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      mobile_padding_horizontal: '5',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_border_size: '0',
      mobile_background: '#4AC6D2',
      mobile_border_color: '#4AC6D2',
      mobile_align_element: 'center',
      mobile_background_image: '',
    },
    button: {
      title: "Let's go",
      color: '#ffffff',
      font_size: '17',
      background: '#9E15BF',
      border_color: '#9E15BF',
      border_size: '0',
      radius: '6',
      visible: true,
      mobile_title: 'Go',
      mobile_visible: true,
      mobile_color: '#ffffff',
      mobile_font_size: '14',
      mobile_background: '#9E15BF',
      mobile_border_size: '0',
      mobile_radius: '6',
      mobile_border_color: '#9E15BF',
    },
    logo: {
      size: '30',
      radius: '13',
      background: '#704a4a00',
      image: '',
      visible: false,
      mobile_size: '50',
      mobile_radius: '13',
      mobile_background: '#704a4a00',
      mobile_image: '',
      mobile_visible: false,
    },
  },
  {
    banner: {
      margin_top: '0',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '15',
      radius: 0,
      background: '#f92727',
      background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659547380796.webp?=1659547381549',
      border_color: '#214259',
      border_size: '0',
      align_element: 'center',
      mobile_padding_horizontal: '5',
      mobile_padding_vertical: '15',
      mobile_radius: '0',
      mobile_background: '#f92727',
      mobile_background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659547380796.webp?=1659547381567',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_align_element: 'center',
      image_repeat: false,
      mobile_image_repeat: false,
      image_size: 'cover',
      mobile_image_size: 'cover',
      image_position: 'top',
      mobile_image_position: 'left',
      show_button_close: true,
      mobile_show_button_close: true,
      background_button_close: '#ffffff',
      mobile_background_button_close: '#ffffff',
      size_button_close: '20',
      color_button_close: '#515151',
      mobile_color_button_close: '#515151',
      mobile_size_button_close: '12',
    },
    logo: {
      visible: false,
      image: '',
      background: '#214259',
      radius: 0,
      mobile_visible: false,
      mobile_image: '',
      mobile_background: '#214259',
      mobile_radius: 0,
      size: '0',
      mobile_size: '0',
    },
    text: {
      visible: true,
      title: 'New Year Sale',
      color: '#fafbfb',
      font_size: '48',
      font: 'Lora',
      mobile_visible: true,
      mobile_title: 'New Year Sale',
      mobile_color: '#fafbfb',
      mobile_font_size: '20',
      mobile_font: 'Lora',
    },
    button: {
      visible: true,
      title: 'Get Discount',
      color: '#fafbfb',
      font_size: '18',
      font: 'Ubuntu',
      border_color: '#214259',
      border_size: 0,
      background: '#271036',
      radius: '5',
      mobile_visible: true,
      mobile_title: 'Get Discount',
      mobile_color: '#fafbfb',
      mobile_font_size: '18',
      mobile_font: 'Ubuntu',
      mobile_border_color: '#f4f4f4',
      mobile_border_size: '1',
      mobile_background: '#271036',
      mobile_radius: '5',
    },
  },
  {
    banner: {
      margin_top: '0',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '15',
      radius: 0,
      background: '#f92727',
      background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659548436860.webp?=1659548438075',
      border_color: '#214259',
      border_size: '0',
      align_element: 'center',
      mobile_padding_horizontal: '5',
      mobile_padding_vertical: '15',
      mobile_radius: '0',
      mobile_background: '#f92727',
      mobile_background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659548436860.webp?=1659548438095',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_align_element: 'center',
      image_repeat: false,
      mobile_image_repeat: false,
      image_size: 'cover',
      mobile_image_size: 'cover',
      image_position: 'center',
      mobile_image_position: 'left',
      show_button_close: true,
      mobile_show_button_close: true,
      background_button_close: '#ffffff',
      mobile_background_button_close: '#ffffff',
      size_button_close: '20',
      color_button_close: '#515151',
      mobile_color_button_close: '#515151',
      mobile_size_button_close: '12',
    },
    logo: {
      visible: false,
      image: '',
      background: '#214259',
      radius: 0,
      mobile_visible: false,
      mobile_image: '',
      mobile_background: '#214259',
      mobile_radius: 0,
      size: '0',
      mobile_size: '0',
    },
    text: {
      visible: true,
      title: 'Holiday sale',
      color: '#fafbfb',
      font_size: '48',
      font: 'Kalam',
      mobile_visible: true,
      mobile_title: 'Holiday sale',
      mobile_color: '#fafbfb',
      mobile_font_size: '20',
      mobile_font: 'Kalam',
    },
    button: {
      visible: true,
      title: 'Get Discount',
      color: '#fafbfb',
      font_size: '20',
      font: 'Asap',
      border_color: '#000000',
      border_size: '5',
      background: '#271036',
      radius: '0',
      mobile_visible: true,
      mobile_title: 'Get Discount',
      mobile_color: '#ffffff',
      mobile_font_size: '16',
      mobile_font: 'Asap',
      mobile_border_color: '#000000',
      mobile_border_size: '5',
      mobile_background: '#000000',
      mobile_radius: '0',
    },
  },
  {
    banner: {
      margin_top: '0',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '15',
      radius: 0,
      background: '#f9272700',
      background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659548985267.png?=1659548986698',
      border_color: '#214259',
      border_size: '0',
      align_element: 'center',
      mobile_padding_horizontal: '5',
      mobile_padding_vertical: '15',
      mobile_radius: '0',
      mobile_background: '#f9272700',
      mobile_background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659548985267.png?=1659548986714',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_align_element: 'center',
      image_repeat: false,
      mobile_image_repeat: false,
      image_size: 'cover',
      mobile_image_size: 'cover',
      image_position: 'center',
      mobile_image_position: 'right',
      show_button_close: true,
      mobile_show_button_close: true,
      background_button_close: '#ffffff',
      mobile_background_button_close: '#ffffff',
      size_button_close: '20',
      color_button_close: '#515151',
      mobile_color_button_close: '#515151',
      mobile_size_button_close: '12',
    },
    logo: {
      visible: false,
      image: '',
      background: '#214259',
      radius: 0,
      mobile_visible: false,
      mobile_image: '',
      mobile_background: '#214259',
      mobile_radius: 0,
      size: '0',
      mobile_size: '0',
    },
    text: {
      visible: true,
      title: 'SPRING SALE',
      color: '#fafbfb',
      font_size: '48',
      font: 'Bitter',
      mobile_visible: true,
      mobile_title: 'SPRING SALE',
      mobile_color: '#fafbfb',
      mobile_font_size: '20',
      mobile_font: 'Bitter',
    },
    button: {
      visible: true,
      title: 'Get Discount',
      color: '#ffffff',
      font_size: '20',
      font: 'Bitter',
      border_color: '#000000',
      border_size: '0',
      background: '#efd7d7',
      radius: '30',
      mobile_visible: true,
      mobile_title: 'Get Discount',
      mobile_color: '#ffffff',
      mobile_font_size: '16',
      mobile_font: 'Bitter',
      mobile_border_color: '#000000',
      mobile_border_size: '0',
      mobile_background: '#efd7d7',
      mobile_radius: '30',
    },
  },
  {
    banner: {
      margin_top: '0',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '15',
      radius: '0',
      background: '#f9272700',
      background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659550842273.webp?=1659550843201',
      border_color: '#214259',
      border_size: '0',
      align_element: 'center',
      mobile_padding_horizontal: '5',
      mobile_padding_vertical: '15',
      mobile_radius: '0',
      mobile_background: '#f9272700',
      mobile_background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659550842273.webp?=1659550843220',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_align_element: 'center',
      image_repeat: false,
      mobile_image_repeat: false,
      image_size: 'cover',
      mobile_image_size: 'cover',
      image_position: 'bottom',
      mobile_image_position: 'center',
      show_button_close: true,
      mobile_show_button_close: true,
      background_button_close: '#ffffff',
      mobile_background_button_close: '#ffffff',
      size_button_close: '20',
      color_button_close: '#005095',
      mobile_color_button_close: '#005095',
      mobile_size_button_close: '12',
    },
    logo: {
      visible: false,
      image: '',
      background: '#214259',
      radius: 0,
      mobile_visible: false,
      mobile_image: '',
      mobile_background: '#214259',
      mobile_radius: 0,
      size: '0',
      mobile_size: '0',
    },
    text: {
      visible: true,
      title: 'SUMMER SALE',
      color: '#0d3152',
      font_size: '48',
      font: 'Vollkorn',
      mobile_visible: true,
      mobile_title: 'SUMMER SALE',
      mobile_color: '#0d3152',
      mobile_font_size: '24',
      mobile_font: 'Vollkorn',
    },
    button: {
      visible: true,
      title: 'Get Discount',
      color: '#ffffff',
      font_size: '20',
      font: 'Vollkorn',
      border_color: '#0d3152',
      border_size: '0',
      background: '#877e85c0',
      radius: '0',
      mobile_visible: true,
      mobile_title: 'Get Discount',
      mobile_color: '#ffffff',
      mobile_font_size: '20',
      mobile_font: 'Vollkorn',
      mobile_border_color: '#005095',
      mobile_border_size: '0',
      mobile_background: '#877e85c0',
      mobile_radius: '0',
    },
  },
  {
    banner: {
      margin_top: '0',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '15',
      radius: 0,
      background: '#f9272700',
      background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659549392705.png?=1659549393621',
      border_color: '#214259',
      border_size: '0',
      align_element: 'center',
      mobile_padding_horizontal: '5',
      mobile_padding_vertical: '15',
      mobile_radius: '0',
      mobile_background: '#f9272700',
      mobile_background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659549392705.png?=1659549393641',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_align_element: 'center',
      image_repeat: false,
      mobile_image_repeat: false,
      image_size: 'cover',
      mobile_image_size: 'cover',
      image_position: 'center',
      mobile_image_position: 'right',
      show_button_close: true,
      mobile_show_button_close: true,
      background_button_close: '#ffffff',
      mobile_background_button_close: '#ffffff',
      size_button_close: '20',
      color_button_close: '#515151',
      mobile_color_button_close: '#515151',
      mobile_size_button_close: '12',
    },
    logo: {
      visible: false,
      image: '',
      background: '#214259',
      radius: 0,
      mobile_visible: false,
      mobile_image: '',
      mobile_background: '#214259',
      mobile_radius: 0,
      size: '0',
      mobile_size: '0',
    },
    text: {
      visible: true,
      title: ' FALL SALE',
      color: '#fafbfb',
      font_size: '48',
      font: 'Bitter',
      mobile_visible: true,
      mobile_title: ' FALL SALE',
      mobile_color: '#fafbfb',
      mobile_font_size: '20',
      mobile_font: 'Bitter',
    },
    button: {
      visible: true,
      title: 'Get Discount',
      color: '#ffffff',
      font_size: '20',
      font: 'Bitter',
      border_color: '#000000',
      border_size: '0',
      background: '#f3ca31cd',
      radius: '0',
      mobile_visible: true,
      mobile_title: 'Get Discount',
      mobile_color: '#ffffff',
      mobile_font_size: '16',
      mobile_font: 'Bitter',
      mobile_border_color: '#000000',
      mobile_border_size: '0',
      mobile_background: '#f3ca31cd',
      mobile_radius: '0',
    },
  },
  {
    banner: {
      margin_top: '0',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '15',
      radius: '0',
      background: '#f9272700',
      background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659549846612.png?=1659549847004',
      border_color: '#214259',
      border_size: '0',
      align_element: 'center',
      mobile_padding_horizontal: '5',
      mobile_padding_vertical: '15',
      mobile_radius: '0',
      mobile_background: '#f9272700',
      mobile_background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659549846612.png?=1659549847018',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_align_element: 'center',
      image_repeat: false,
      mobile_image_repeat: false,
      image_size: 'cover',
      mobile_image_size: 'cover',
      image_position: 'center',
      mobile_image_position: 'center',
      show_button_close: true,
      mobile_show_button_close: true,
      background_button_close: '#ffffff',
      mobile_background_button_close: '#ffffff',
      size_button_close: '20',
      color_button_close: '#005095',
      mobile_color_button_close: '#005095',
      mobile_size_button_close: '12',
    },
    logo: {
      visible: false,
      image: '',
      background: '#214259',
      radius: 0,
      mobile_visible: false,
      mobile_image: '',
      mobile_background: '#214259',
      mobile_radius: 0,
      size: '0',
      mobile_size: '0',
    },
    text: {
      visible: true,
      title: 'WINTER SALE',
      color: '#0d3152',
      font_size: '48',
      font: 'Vollkorn',
      mobile_visible: true,
      mobile_title: 'WINTER SALE',
      mobile_color: '#0d3152',
      mobile_font_size: '24',
      mobile_font: 'Vollkorn',
    },
    button: {
      visible: true,
      title: 'Get Discount',
      color: '#ffffff',
      font_size: '20',
      font: 'Vollkorn',
      border_color: '#0d3152',
      border_size: '0',
      background: '#005095c0',
      radius: '22',
      mobile_visible: true,
      mobile_title: 'Get Discount',
      mobile_color: '#ffffff',
      mobile_font_size: '20',
      mobile_font: 'Vollkorn',
      mobile_border_color: '#005095',
      mobile_border_size: '0',
      mobile_background: '#005095c0',
      mobile_radius: '22',
    },
  },
  {
    banner: {
      margin_top: '0',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '15',
      radius: '0',
      background: '#f9272700',
      background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659551539224.webp?=1659551540076',
      border_color: '#214259',
      border_size: '0',
      align_element: 'center',
      mobile_padding_horizontal: '5',
      mobile_padding_vertical: '15',
      mobile_radius: '0',
      mobile_background: '#f9272700',
      mobile_background_image:
        'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1659551539224.webp?=1659551540096',
      mobile_border_color: '#214259',
      mobile_border_size: '0',
      mobile_align_element: 'center',
      image_repeat: false,
      mobile_image_repeat: false,
      image_size: 'cover',
      mobile_image_size: 'cover',
      image_position: 'bottom',
      mobile_image_position: 'left',
      show_button_close: true,
      mobile_show_button_close: true,
      background_button_close: '#ffffff',
      mobile_background_button_close: '#ffffff',
      size_button_close: '20',
      color_button_close: '#005095',
      mobile_color_button_close: '#005095',
      mobile_size_button_close: '12',
    },
    logo: {
      visible: false,
      image: '',
      background: '#214259',
      radius: 0,
      mobile_visible: false,
      mobile_image: '',
      mobile_background: '#214259',
      mobile_radius: 0,
      size: '0',
      mobile_size: '0',
    },
    text: {
      visible: true,
      title: " Mother's Day Sale",
      color: '#ffffff',
      font_size: '48',
      font: 'Vollkorn',
      mobile_visible: true,
      mobile_title: " Mother's Day Sale",
      mobile_color: '#ffffff',
      mobile_font_size: '24',
      mobile_font: 'Vollkorn',
    },
    button: {
      visible: true,
      title: 'Get Discount',
      color: '#ffffff',
      font_size: '20',
      font: 'Vollkorn',
      border_color: '#0d3152',
      border_size: '0',
      background: '#ef9295',
      radius: '0',
      mobile_visible: true,
      mobile_title: 'Get Discount',
      mobile_color: '#ffffff',
      mobile_font_size: '20',
      mobile_font: 'Vollkorn',
      mobile_border_color: '#005095',
      mobile_border_size: '0',
      mobile_background: '#ef9295',
      mobile_radius: '0',
    },
  },
  {
    text: {
      title: 'HOLIDAY SALE: Save 25% OFF With Promo Code: HOLIDAY25 ❄️',
      color: '#ffffff',
      font_size: '18',
      visible: true,
      mobile_title: 'HOLIDAY SALE: Save 25% OFF With Promo Code: HOLIDAY25 ❄️',
      mobile_visible: true,
      mobile_color: '#ffffff',
      mobile_font_size: '14',
    },
    banner: {
      margin_top: '0',
      margin_horizontal: '0',
      padding_horizontal: '5',
      padding_vertical: '5',
      radius: '0',
      border_size: '0',
      background: '#78aee7',
      border_color: '#78aee7',
      align_element: 'center',
      background_image: '',
      mobile_margin_top: '0',
      mobile_margin_horizontal: '0',
      mobile_padding_horizontal: '8',
      mobile_padding_vertical: '5',
      mobile_radius: '0',
      mobile_border_size: '0',
      mobile_background: '#78aee7',
      mobile_border_color: '#78aee7',
      mobile_align_element: 'center',
      mobile_background_image: '',
    },
    button: {
      title: 'Learn More',
      color: '#000000',
      font_size: '15',
      background: '#FAD43E',
      border_color: '#FAD43E',
      border_size: '0',
      radius: '5',
      visible: false,
      mobile_title: 'Learn More',
      mobile_visible: false,
      mobile_color: '#000000',
      mobile_font_size: '11',
      mobile_background: '#FAD43E',
      mobile_border_size: '0',
      mobile_radius: '5',
      mobile_border_color: '#FAD43E',
    },
    logo: {
      size: '30',
      radius: '0',
      background: '#ffffff00',
      image: '',
      visible: false,
      mobile_size: '50',
      mobile_radius: '0',
      mobile_background: '#ffffff00',
      mobile_image: '',
      mobile_visible: false,
    },
  }
]
  const other = [
    {
      text: {
        title: 'Exclusive Offers on Covid Care Equipments',
        color: '#ffffff',
        font_size: '16',
        visible: true,
        mobile_title: 'Exclusive Offers on Covid Care Equipments',
        mobile_visible: true,
        mobile_color: '#ffffff',
        mobile_font_size: '16',
        font: 'Josefin Sans',
        mobile_font: 'Josefin Sans'
      },
      banner: {
        margin_top: '0',
        margin_horizontal: '0',
        padding_horizontal: '5',
        padding_vertical: '5',
        radius: '0',
        border_size: '0',
        background: '#232323',
        border_color: '#000000',
        align_element: 'center',
        background_image: '',
        mobile_margin_top: '0',
        mobile_margin_horizontal: '0',
        mobile_padding_horizontal: '8',
        mobile_padding_vertical: '5',
        mobile_radius: '0',
        mobile_border_size: '0',
        mobile_background: '#232323',
        mobile_border_color: '#000000',
        mobile_align_element: 'center',
        mobile_background_image: ''
      },
      button: {
        title: 'Shop now',
        color: '#ffffff',
        font_size: '16',
        background: '#e20027',
        border_color: '#e20027',
        border_size: '3',
        radius: '5',
        visible: true,
        mobile_title: 'Shop now',
        mobile_visible: true,
        mobile_color: '#ffffff',
        mobile_font_size: '16',
        mobile_background: '#e20027',
        mobile_border_size: '3',
        mobile_radius: '5',
        mobile_border_color: '#e20027',
        font: 'Open Sans',
        mobile_font: 'Open Sans'
      },
      logo: {
        size: '30',
        radius: '0',
        background: '#ffffff00',
        image: 'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1675189462303.png?=1675189462741',
        visible: true,
        mobile_size: '50',
        mobile_radius: '0',
        mobile_background: '#ffffff00',
        mobile_image: 'https://netvision.nyc3.digitaloceanspaces.com/images/listat.myshopify.com/img_1675189462303.png?=1675189462765',
        mobile_visible: true
      }
    }
];

function ChangeTheme({ changeRoot }) {
  const [active, setActive] = useState(false);

  const handleChange = () => {
    setActive(false);
  };

  const themes = {
    Top: tops,
    'Free shipping': freeshipping,
    // 'Valentine’s Day': valentinesDay,
    'Sales': sales,
    // Halloween: halloween,
    // 'Black friday': blackFriday,
    'Holidays': holidays,
    'Other': other
  };

  const activator = (
    <Button fullWidth outline onClick={() => setActive(true)}>
      Change theme
    </Button>
  );

  return (
    <Modal
      activator={activator}
      open={active}
      onClose={handleChange}
      footer={false}
      title="Theme baners"
      large
    >
      <Modal.Section>
        <div className={styles.ChangeTheme}>
          {Object.keys(themes).map((key) => (
            <>
              <div className={styles.title}>{key}</div>
              {themes[key].map((_i, index) => (
                <div key={'thme_' + index} className={styles.item}>
                  <div
                    className={styles.block}
                    onClick={() => {
                      changeRoot('setting', _i);
                      handleChange();
                    }}
                  />
                  {/* <Banner settings={_i} /> */}
                </div>
              ))}
            </>
          ))}
        </div>
      </Modal.Section>
    </Modal>
  );
}

export default ChangeTheme;
